- name: copying the mongodb repo file
  ansible.builtin.copy:
    src : mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name : install mongodb package
  ansible.builtin.package:
    name : mongodb-org
    state : present

- name : Enable and start sysyemctl
  ansible.builtin.service:
    name : mongod
    state: started
    enabled: yes

- name : replacing the remote connection to allow
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name : restart the mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted