- name : app setup file importing here
  ansible.builtin.import_role:
    name : common                                #folder/ role name present inside roles folder
    tasks_from: app-setup

- name : go installation file importing
  ansible.builtin.import_role:
    name : common           
    tasks_from: go


- name : setting up systemctl service things like deamonreload restart and enable 
  ansible.builtin.import_role:
    name : common          
    tasks_from: systemd