#these all tasks are common for some module so we r keeping here like user,cart,catalogue etc
- name : creating user roboshop
  ansible.builtin.user:
    name : roboshop

- name : recursively remove app directory if its present
  ansible.builtin.file:
    path : /app
    state : absent
    
- name : creating app directory
  ansible.builtin.file:
    path : /app
    state: directory

# #normal use
# - name : "downloading the {{component}} application"
#   ansible.builtin.get_url:
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: /tmp

# - name : "unzipping the {{component}}.js file"
#   ansible.builtin.unarchive:
#     src: "/tmp/{{component}}.zip"
#     dest: /app
#     remote_src: yes

      #for nexus repo
- name : "download the artifact from nexus"
  ansible.builtin.get_url:
    url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: /tmp
    # username: "{{username}}"
    # password: "{{password}}"

- name : "extract the {{component}} file"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes


